module.exports =  {
    CREATE_AUTHOR: 'CREATE_AUTHOR',
    READ_AUTHOR: 'READ_AUTHOR',
    UPDATE_AUTHOR: 'UPDATE_AUTHOR',
    DELETE_AUTHOR: 'DELETE_AUTHOR',
    
    CREATE_BOOK: 'CREATE_BOOK',
    READ_BOOK: 'READ_BOOK',
    UPDATE_BOOK: 'UPDATE_BOOK',
    DELETE_BOOK: 'DELETE_BOOK',

    CREATE_CATEGORY: 'CREATE_CATEGORY',
    READ_CATEGORY: 'READ_CATEGORY',
    UPDATE_CATEGORY: 'UPDATE_CATEGORY',
    DELETE_CATEGORY: 'DELETE_CATEGORY',

    CREATE_PROFILE: 'CREATE_PROFILE',
    READ_PROFILE: 'READ_PROFILE',
    UPDATE_PROFILE: 'UPDATE_PROFILE',
    DELETE_PROFILE: 'DELETE_PROFILE',
};
